version: 2

jobs:
  build:
    working_directory: ~/share/htdocs
    docker:
      - image: circleci/php:5.6-node-browsers-legacy
      - image: circleci/mysql:5.6
    steps:
      - run:
            command: echo "build..."
      - checkout
      - deploy:
          name: conditionally run a deploy job
          command: |
            # replace this with your build/deploy check (i.e. current branch is "release")
            if [[ true ]]; then
              curl \
                --data build_parameters[CIRCLE_JOB]=deployment \
                --data build_parameters[CI_REMOTE_BUILD_RELEASE]=1 \
                https://circleci.com/api/v1.1/project/github/akanenoan/ci_test/tree/develop?circle-token=2104ff7c2f32118ae5177046f57bed0a22b644f6
            fi
  deployment:
    working_directory: ~/share/htdocs
    docker:
      - image: circleci/php:5.6-node-browsers-legacy
    steps:
      - run:
            command: echo "deployment..."
workflows:
  version: 2
  features:
    jobs:
      - build:
          filters:
            branches:
              only: /feature\/.+/
  integration:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - deployment:
          requires:
            - build
          filters:
            branches:
              only: develop
  staging:
    jobs:
      - build:
          filters:
            branches:
              only: /(release|hotfix)\/.+/
      - deployment:
          requires:
            - build
          filters:
            branches:
              only: /(release|hotfix)\/.+/
  production:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deployment:
          requires:
            - build
          filters:
            branches:
              only: master
