version: 2

jobs:
  build:
    environment: &environment
      # CircleCI API Base URI
      CI_API_BASE: "https://circleci.com/api/v1.1"

    working_directory: ~/share/htdocs
    docker:
      - image: circleci/php:5.6-node-browsers-legacy
      - image: circleci/mysql:5.6
    steps:
      - run:
            command: echo "build..."
      - checkout
      - deploy:
          name: conditionally run a deploy job
          command: |
            # replace this with your build/deploy check (i.e. current branch is "release")
            if [[ "${CI_REMOTE_BUILD_RELEASE}" == 1 ]]; then
              echo "run deployment..."
              echo ${CI_REMOTE_TAG_RELEASE}
              echo ${CI_API_TOKEN}
              echo $CI_API_TOKEN
              echo $CIRCLE_PROJECT_USERNAME
              echo $CIRCLE_PROJECT_REPONAME
              echo $CIRCLE_BRANCH
              curl \
                --data build_parameters[CIRCLE_JOB]=deployment \
                --data build_parameters[CI_REMOTE_BUILD_RELEASE]=1 \
                --data build_parameters[CI_REMOTE_TAG_RELEASE]=${CI_REMOTE_TAG_RELEASE} \
                ${CI_API_BASE}/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH?circle-token=${CI_API_TOKEN}
            fi
  deployment:
    working_directory: ~/share/htdocs
    docker:
      - image: circleci/php:5.6-node-browsers-legacy
    steps:
      - run:
            command: echo "deployment..."
workflows:
  version: 2
  features:
    jobs:
      - build:
          filters:
            branches:
              only: /feature\/.+/
  integration:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - deployment:
          requires:
            - build
          filters:
            branches:
              only: develop
  staging:
    jobs:
      - build:
          filters:
            branches:
              only: /(release|hotfix)\/.+/
      - deployment:
          requires:
            - build
          filters:
            branches:
              only: /(release|hotfix)\/.+/
  production:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deployment:
          requires:
            - build
          filters:
            branches:
              only: master
